### ISSUE TITLE
how to use  openai.ChatCompletion.create? 

### ISSUE THREAD

**Issue by mail2harishemail** [UIUC-Chatbot/llm-serving#3]
def chat_completions():
    result = openai.ChatCompletion.create(
        model="irrelevant", messages=[{"role": "user", "content": "Hello!"}]
    )
  This is not working any plan to implement ?

**Comment by KastanDay** [comment]
Hey thanks, but bad news; this project is very early and not ready for users yet.

I'm building a wrapper around VLLM to support multiple models, ideally 100% of the models on huggingface. TBD. 

Check out [vllm](https://github.com/vllm-project/vllm) for some great work on this.

**Comment by KastanDay** [comment]
and YES, I will support `ChatCompletion` soon.
